version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Phoenix
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "08:15"
      timezone: America/Phoenix
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
      include: scope
